/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-ac0.asn"
 * 	`asn1c -S /home/nyee/srsLTE/srslte/examples/src/asn1c/skeletons -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_PhyLayerParameters_H_
#define	_PhyLayerParameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PhyLayerParameters */
typedef struct PhyLayerParameters {
	BOOLEAN_t	 ue_TxAntennaSelectionSupported;
	BOOLEAN_t	 ue_SpecificRefSigsSupported;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PhyLayerParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PhyLayerParameters;

#ifdef __cplusplus
}
#endif

#endif	/* _PhyLayerParameters_H_ */
#include <asn_internal.h>
