/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-ac0.asn"
 * 	`asn1c -S /home/nyee/srsLTE/srslte/examples/src/asn1c/skeletons -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_RegisteredMME_H_
#define	_RegisteredMME_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include "MMEC.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PLMN_Identity;

/* RegisteredMME */
typedef struct RegisteredMME {
	struct PLMN_Identity	*plmn_Identity	/* OPTIONAL */;
	BIT_STRING_t	 mmegi;
	MMEC_t	 mmec;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegisteredMME_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RegisteredMME;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PLMN-Identity.h"

#endif	/* _RegisteredMME_H_ */
#include <asn_internal.h>
